spring:
  application:
    name: core-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  config:
    import: optional:configserver:http://localhost:8888
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs