spring:
  data:
    redis:
      port: 6379
      host: localhost
server:
  port:
    8093
application:
  userService:
    baseUri: http://localhost:8222/api/v1/users
  open-api:
    server: http://127.0.0.1:8222
    email: someemail
