server:
  port: 8222
spring:
  security:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/carts/**, /api/v1/categories/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - CustomAuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - CustomAuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: image-service
          uri: lb://image-service
          predicates:
              - Path=/api/v1/images/**
          filters:
            - CustomAuthenticationFilter
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedHeaders:
            - "*"
          allowedMethods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
      default-filters:
        - name: Retry
          args:
#            retries: 3
            methods: GET,POST,PUT,DELETE,OPTIONS

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    authenticationServiceUri: http://auth-service/api/v1/auth/verify
    publicUrls:
      - api/v1/auth/login
      - api/v1/auth/register
      - api/v1/auth/verify


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
